name: Slate documentation builder
author: Decathlon <developers@decathlon.com>
description: This Github action <strong>builds repositories Markdown files</strong> using slate framework. The slate build result will be stored into the build subdirectory of <md files folder>.
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: tag
  color: blue
