on: push
name: Create Slate Documentation on Push
jobs:
  action-filter:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build documentation
      uses: ./
      env:
        DOC_BASE_FOLDER: ./test-documentation/
        ZIP_BUILD: false
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: test-documentation/build 
